<div id="three-columns">
  <div class="row">
    <div class="wrapper-three-columns">
      <div class="mustang">
        <img src="">
        <span></span>
        <h6></h6>
        <hr>
        <p></p>
        <a href="#">READ MORE</a>
      </div>
      <div class="bugatti">
        <img src="">
        <span></span>
        <h6></h6>
        <hr>
        <p></p>
        <a href="#">READ MORE</a>
      </div>
      <div class="mercedes">
        <img src="">
        <span></span>
        <h6></h6>
        <hr>
        <p></p>
        <a href="#">READ MORE</a>
      </div>
    </div>
  </div>
</div>
